services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - 3005:3005
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
      - /Users/guang/mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: meeting_room_booking_system
      MYSQL_ROOT_PASSWORD: lengran
    networks:
      - common-network
    ports:
      - 3306:3306
  redis-container:
    image: redis
    volumes:
      - /Users/guang/mysql-data:/var/lib/mysql
    networks:
      - common-network
    ports:
      - 6379:6379
networks:
  common-network:
    driver: bridge
